# Generated by Django 4.2.23 on 2025-07-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_number', models.CharField(max_length=100)),
                ('bap_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
