# Generated by Django 4.2.23 on 2025-07-18 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_projecttype_projectassignment_addusersubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='name',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttype',
            name='type',
            field=models.CharField(default='Internal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exardproduct',
            name='project_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='AddUserSubmission',
        ),
        migrations.DeleteModel(
            name='ProjectAssignment',
        ),
    ]
