# Generated by Django 4.2.23 on 2025-07-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_adduser_remove_projectassignment_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exardproduct',
            name='bap_number',
        ),
        migrations.RemoveField(
            model_name='exardproduct',
            name='project_type',
        ),
    ]
