# Generated by Django 4.2.23 on 2025-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_exardproduct_bap_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exardproduct',
            name='alpha_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
